config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :orders
resources :menus


get 'signup', to: 'users#new'
resources :users, except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

root 'welcomes#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    validates :item, presence: true, length: {minimum: 3, maximum: 10}
    validates :drink, presence: true, length: {minimum: 3, maximum: 100}
    validates :room, presence: true, length: {minimum: 3, maximum: 500}
    validates :description, presence: true, length: {minimum: 3, maximum: 500}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :orders, dependent: :destroy
    before_save { self.email = email.downcase }
     validates :username, presence: true, 
                uniqueness: { case_sensitive: false },
                length: { minimum: 3, maximum: 25 }
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 105 },
                uniqueness: { case_sensitive: false },
                format: { with: VALID_EMAIL_REGEX }
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
   def current_user
       #return current user if it alread exit if not find the user based on id in session
       @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end
   
    def logged_in?
        # !! converts to a boolean
         !!current_user
    end
    
     def require_user
          if !logged_in?
               flash[:danger] = "You must be logged in to perform that action"
               redirect_to root_path
          end
     end
     
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 before_action :set_order, only: [:edit, :update, :show, :destroy]
 before_action :require_user, except: [:index, :show]
 before_action :require_same_user, only: [:edit, :update, :destroy]
 
 def index
     @orders = Order.all
 end
 
 def new
     @order = Order.new
 end
 
 def edit
     
 end
 
 def update
     
     if @order.update(order_params)
          flash[:success] = "Order was successfully updated"
          redirect_to order_path(@order)
     else
         render 'edit'
     end
 end
 
 def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
         flash[:success] = "Order was successfully created"
         redirect_to order_path(@order)
    else
        render 'new'
    end
 end
 
 def show
    
 end
 
 def destroy
     
     @order.destroy
     flash[:danger] = "Order item was removed from history"
     redirect_to orders_path(@order)
 end
 
private
 def set_order
     @order = Order.find(params[:id])
 end
 
 def order_params
   params.require(:order).permit(:item, :drink, :room, :description)
 end
  
 def require_same_user
  if current_user != @order.user and !current_user.admin?
   flash[:danger] = "You can only edit or delete your own orders"
   redirect_to root_path
  end
 end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:success] = "You have successfully logged in"
             redirect_to user_path(user)
        else
            flash.now[:danger] = "There was something wrong with your login information"
            render 'new'
        end
    end

    def destroy
         session[:user_id] = nil
         flash[:success] = "You have logged out"
          redirect_to root_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    before_action :require_admin, only: [:destroy]
    
    def new
         @user = User.new
    end
    
    def index
         @users = User.all
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
             session[:user_id] = @user.id
            flash[:success] = "Welcome to 49ner Food Express #{@user.username}"
             redirect_to user_path(@user)
        else
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to orders_path
        else
            render 'edit'
        end
    end
    
    def show
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "User and all orders created by user have been deleted"
        redirect_to users_path
    end
    
private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end 
    
    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
        if current_user != @user and !current_user.admin?
            flash[:danger] = "You can only edit your own account"
            redirect_to root_path
        end
    end
    
    def require_admin
        if logged_in? and !current_user.admin?
            flash[:danger] = "Only admin users can perform that action"
            redirect_to root_path
        end
    end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def new
     redirect_to orders_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})
         gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
         size = options[:size]
         gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
         image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
end

app/views/layouts/_messages.html.erb
<div class="row">
<div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg| %>
<div class='alert alert-<%="#{name}" %>'>
<a href="#" class="close" data-dismiss="alert">&#215;</a> <!-- give me a small x symbol to close out message-->
<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
</div>
<% end %>
</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '49er Food Express', root_path, class: "navbar-brand", id: "logo" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Menu", controller: "menus"%></li>
        <li><%= link_to "Orders", orders_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "New Order", new_order_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View your profile", user_path(current_user) %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
           <li><%= link_to 'Log in', login_path %></li>
           <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodexpressAlpha</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
<!-- _messages.html.erb-->    
   <div class="container">
  <%= yield %>
  </div>
  </body>
</html>

app/views/menus/index.html.erb
<h1>Welcome to 49er Food Express Menu!</h1>
<div class="row">
  <div class="plans clearfix">
    <div class="col-lg-3 col-lg-offset-3 plan">
      <h2>Chick-fil-A</h2>
      <div class="features">
        <ul>
          <li>Item 1-1: Chicken Sandwich</li>
          <li>Price: $3.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
          <li>Item 1-2: Spicy Chicken Delux Sandwich</li>
          <li>Price: $4.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
          <li>Item 1-3: Chicken Nuggets</li>
          <li>Price: $3.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
        </ul>
      </div>
      <p>
        <!-- -->
      </p>
    </div>
    
    <div class="col-lg-3 plan">
      <h2>Wendy's</h2>
      <div class="features">
        <ul>
          <li>Item 2-1: Jr. Cheeseburger</li>
          <li>Price: $2.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
          <li>Item 2-2: Baconator</li>
          <li>Price: $4.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
          <li>Item 2-3: Fresh Made Salad</li>
          <li>Price: $4.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
        </ul>
      </div>
      <p>
        <!-- -->
      </p>
      </div>  
      
      <div class="col-lg-3 plan">
      <h2>Bojangles</h2>
      <div class="features">
        <ul>
          <li>Item 3-1: 4 Piece Homestyle Tenders™</li>
          <li>Price: $3.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
          <li>Item 3-2: Cajun Filet Club Sandwich</li>
          <li>Price: $3.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
          <li>Item 3-3: Bacon, Egg and Cheese Biscuit</li>
          <li>Price: $3.99</li>
          <%= link_to 'Order', new_order_path, class: 'btn btn-primary sign-up' %>
        </ul>
      </div>
      <p>
        <!-- -->
      </p>
      <div class="col-lg-3 plan">
      <h2>Drinks</h2>
      <div class="features">
        <ul>
          <li>coke</li>
          <li>sweet tea</li>
          <li>pepsi</li>
          <li>orange jiuce</li>
        </ul>
      </div>
      <p>
        <!--<div class="price pull-right"> -->
      </p>
    </div>
</div>
</div>

app/views/orders/_form.html.erb
<!-- this is to stop the redundancy in the edit and new html files
this file will have the code that is needed for both the edit and new html-->
<!--the following will be sent to the new.htmlerb and the edit.html.erb-->

<%= render 'shared/errors', obj: @order %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@order, :html => {class: "form-horizontal", role: "form"}) do |f| %> <!--the form horizontal makes everything even with the text area-->
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :item %>
     </div>
     <div class="col-sm-8">
      <%= f.text_field :item, class: "form-control", placeholder: "Order item", autofocus: true %>
     </div>
    </div>
    
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :drink %>
     </div>
     <div class="col-sm-8">
      <%= f.text_field :drink, class: "form-control", placeholder: "Drink", autofocus: true %>
     </div>
    </div>
    
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :room %>
     </div>
     <div class="col-sm-8">
      <%= f.text_field :room, class: "form-control", placeholder: "Room number", autofocus: true %>
     </div>
    </div>
    
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :description %>
     </div>
     <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control", placeholder: "Add description", autofocus: true %>
     </div>
    </div>
    
   <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10"> <!-- the offset indents the submit button -->
     <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
   </div>
    <% end %>
   <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to order history", orders_path %> ] 
 </div>
</div> 

app/views/orders/_order.html.erb
 <% obj.each do |order| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="order-item">
     <%= link_to order.item, order_path(order) %>
    </div>
     <div class="order-body">
      <%= truncate(order.description, length: 100) %>
      <div class="order-meta-details">
       <small>Created by: <%= order.user.username if order.user %>,
             <%= time_ago_in_words(order.created_at) %> ago,
             last updated: <%= time_ago_in_words(order.updated_at) %> ago</small>
      </div>
     </div>
      <% if logged_in? && (current_user == order.user || current_user.admin?) %>
        <div class="order-actions">
         <%= link_to "Edit this order", edit_order_path(order), class: "btn btn-xs btn-primary" %>
         <%= link_to "Delete this order", order_path(order), method: :delete,
                                       data: { confirm: "Are you sure you want to delete the order?"},
                                       class: "btn btn-xs btn-danger" %>
        </div>
      <% end %>
   </div>
  </div>
 </div> 
 <% end %>

app/views/orders/edit.html.erb
<h1 align="center">Edit existing order</h1>
<!-- get the information from the _form.html.erb and puts it in here -->
<%= render 'form' %>

app/views/orders/index.html.erb
<h1 align="center">Listing all orders</h1>


<%= render 'order', obj: @orders %>

app/views/orders/new.html.erb
<h1 align="center">Create an order</h1> <!--moves text to center-->
<!-- get the information from the _form.html.erb and puts it in here -->
<%= render 'form' %>

app/views/orders/show.html.erb
<h2 align="center">Item: <%= @order.item %></h2>

<div class="well col-xs-8 col-xs-offset-2">
 <% if @order.user %>
 <ul class="listing">
        <div class="row center">
            <div class="col-md-4 col-md-offset-4">
                <li>Created by:</li>
                <li><%= link_to gravatar_for(@order.user), user_path(@order.user) %></li>
                <li class="order-item">
                    <%= link_to @order.user.username, user_path(@order.user) %>
                </li>
                 <li><small>
                  <%= pluralize(@order.user.orders.count, "order") if @order.user.orders %>
                 </small></li>
            </div>
        </div>  
    </ul>
 <% end %>
 
 <h4 class="center room"><strong>Room:</strong></h4>
 <hr>
 <%= simple_format(@order.room) %>
 
 <h4 class="center description"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@order.description) %>
 
 <div class="order-actions">
   <% if logged_in? && (current_user == @order.user || current_user.admin?) %>
    <%= link_to "Edit this order", edit_order_path(@order), class: "btn btn-xs btn-primary" %>
    <%= link_to "Delete this order", order_path(@order), method: :delete,
                                      data: { confirm: "Are you sure you want to delete the order?"},
                                      class: "btn btn-xs btn-danger" %>
   <% end %>
   
  <%= link_to "View all orders", orders_path, class: "btn btn-xs btn-success" %>
 </div>
</div> 

<!--
<p>
 Drink: <%= @order.drink %>
</p>
-->

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row">

<div class="col-xs-8 col-xs-offset-2">

<div class="panel panel-danger">

<div class="panel-heading">

<h2 class="panel-title">

<%= pluralize(obj.errors.count, "error") %>

prohibited this article from being saved:

</h2>

<div class="panel-body">

<ul>

<% obj.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

</div>

</div>

</div>

</div>

<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='row'>
  <div class='col-xs-12'>
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %> <!--the form horizontal makes everything even with the text area-->
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :username %>
     </div>
     <div class="col-sm-8">
      <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
     </div>
    </div>
    
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :email %>
     </div>
     <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
     </div>
    </div>
    
    <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :password %>
     </div>
     <div class="col-sm-8">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
     </div>
    </div>

   <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10"> <!-- the offset indents the submit button -->
     <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: 'btn btn-primary btn-lg') %>
    </div>
   </div>
    <% end %>
   <div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel request and return to order history", orders_path %> ] 
   </div>
  </div> 
</div> 

app/views/users/edit.html.erb
<h1 align="center">Edit your account Express</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All 49ner Food Express Users</h1>
<div align="center">
    <% @users.each do |user| %>
    <ul class="listing">
        <div class="row">
            <div class="well col-md-4 col-md-offset-4">
                <li><%= link_to gravatar_for(user), user_path(user) %></li>
                <li class="order-item">
                    <%= link_to user.username, user_path(user) %>
                </li>
                 <li><small><%= pluralize(user.orders.count, "order") if user.orders %></small></li>
                 <% if logged_in? and current_user.admin? %>
                     <li><%= link_to "Delete this user", user_path(user), method: :delete,
                         data: { confirm: "Are you sure you want to delete the user and all their orders?" } %></li>
                 <% end %>
            </div>
        </div>  
    </ul>
<% end %>
</div>

        

app/views/users/new.html.erb
<h1 align="center">Sign up for 49ner Food Express</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
         <%= gravatar_for @user, size: 150 %>
    </div>
</div>

<h4 align="center"><%= @user.username %>'s orders</h4>
<%= render 'orders/order', obj: @user.orders %>

app/views/welcomes/new.html.erb
<div class="center jumbotron">
    <h1></h1>
    <%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>